### ISSUE TITLE
[Excalibur] UI polish:

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#300]
- [x] Add descriptions and subheadings https://github.com/Recidiviz/covid19-dashboard/pull/335
- [ ] Add tooltips and hover texts https://github.com/Recidiviz/covid19-dashboard/pull/343 ... @daschi did this in https://github.com/Recidiviz/covid19-dashboard/pull/366! (I was trying to make the tooltip appear on the top in 343, and will still try to get that to work)
- [ ] Pass at final copy

PRD: https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit

MOCKUP: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=1828%3A29

**Comment by amyrlam** [comment]
@sychang Here's where we're at with https://github.com/Recidiviz/covid19-dashboard/pull/335 (not sure what's up with the graph):

![screencapture-localhost-8000-impact-2020-05-07-17_57_12](https://user-images.githubusercontent.com/1372946/81358754-3c513e80-908c-11ea-9827-d3322e55e251.png)

**Comment by daschi** [comment]
@amyrlam Oh no! I'm so sorry I overlapped with your PR, I went down the doc and didn't realize this was part of what you were already working on

**Comment by amyrlam** [comment]
@daschi oh no problem at all! Just was keeping track here

**Comment by amyrlam** [comment]
It was also helpful to see what you did! 

FWIW, I think this can be closed and use https://github.com/Recidiviz/covid19-dashboard/issues/360 instead, will check tmrw

**Comment by amyrlam** [comment]
I think we can close this and move on to https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit# instead!

I will still work on closing https://github.com/Recidiviz/covid19-dashboard/pull/343 this week to adjust the tooltip to have top option vs. right
